"""
Pipeline step 6 — the third research question: does a physics-informed neural
network earn its cost on this problem?

The comparison is run in two stages, and the order matters. A PINN is first
asked to recover parameters from synthetic data generated by the classical
model, where the truth is known and there is no misspecification. Only if it
passes that is its behaviour on real data worth interpreting; a method that
cannot recover parameters it was given has nothing to say about ones it was not.

Both estimators optimise the same negative binomial likelihood over the same
data, so any difference is attributable to the method rather than to the
objective.

The claim under test is not that PINNs are more accurate. It is that their cost
is independent of the cost of a forward solve, which matters only when forward
solves are expensive. This model integrates in about twelve milliseconds, so the
expectation is that the classical estimator wins comfortably — and the useful
result is the size of the gap, since that is what a more expensive model would
have to overcome.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# `dengue_pk` MUST be imported before NumPy, pandas, SciPy or Matplotlib.
# Importing it preloads the system MSVC runtime, and Windows keeps only the first
# DLL loaded under a given name — so if NumPy arrives first it pins Anaconda's
# older copy and TensorFlow then fails to initialise. The ordering is enforced by
# `tests/test_environment.py`. See `dengue_pk/_msvc_runtime.py`.
from dengue_pk import load_config, resolve  # noqa: E402
from dengue_pk.inference import (Dataset, estimate_dispersion_k, fit,  # noqa: E402
                                 nb_loglik, predict)
from dengue_pk.models import FixedParams, basic_reproduction_number  # noqa: E402
from dengue_pk.pinn import InversePINN  # noqa: E402

import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

cfg = load_config()
OBS = cfg["inference"]["observation"]
fixed = FixedParams.from_config(cfg)
processed = resolve(cfg, "processed")
figures = resolve(cfg, "figures")
tables = resolve(cfg, "tables")

rows = []


def score(data, mu, n_params):
    k = estimate_dispersion_k(data.cases, mu)
    ll = nb_loglik(data.cases, mu, k)
    return ll, -2 * ll + 2 * (n_params + 1), k


# ===========================================================================
# Stage 1 — recovery from synthetic data, where the truth is known
# ===========================================================================
print("=" * 78)
print("STAGE 1 — recovery from synthetic data")
print("=" * 78)

rng = np.random.default_rng(cfg["seed"])

# The synthetic truth is calibrated to resemble the observed national wave rather
# than chosen for convenience: 18,050 expected cases peaking at 2,615 in week 42,
# against 17,894 peaking at 2,184 in week 37. Testing recovery in a regime the
# model cannot reach on real data would tell us nothing about its behaviour there.
#
# Calibrating it exposed a model-adequacy problem worth recording. Over most of
# the parameter space the model is either subcritical — a handful of cases — or it
# saturates, infecting essentially the whole population at risk and producing a
# peak four to five times taller than observed. Only a narrow band reproduces a
# wave of the observed height and breadth. The real epidemic is broader and flatter
# than a single-strain, homogeneously mixing model naturally generates, which is
# consistent with the aggregation of regional outbreaks that peak at different
# times.
truth = dict(beta_0=0.17, a_temp=0.2, a_rain=0.1, pop_frac=0.0025,
             i0_frac=5e-6)

ref = pd.read_csv(processed / "national_2013.csv", parse_dates=["week_start"])
template = Dataset.from_frame(ref, label="synthetic")
mu_true = predict(truth, template, fixed, "climate", cfg)
k_true = 5.0
lam = rng.gamma(shape=k_true, scale=np.maximum(mu_true, 1e-12) / k_true)
synth = Dataset(template.days, rng.poisson(lam).astype(float), template.temp_c,
                template.z_rain, template.population, "synthetic")

print(f"truth: R0 = {basic_reproduction_number(truth['beta_0'], fixed):.3f}, "
      f"pop_frac = {truth['pop_frac']}, a_rain = {truth['a_rain']}")

print("\n[classical]")
t0 = time.time()
cls = fit(synth, cfg, fixed, model="climate", observation=OBS)
cls_mu = predict(cls.theta, synth, fixed, "climate", cfg)
cls_ll, cls_aic, _ = score(synth, cls_mu, len(cls.names))
print(f"  R0 = {basic_reproduction_number(cls.theta['beta_0'], fixed):.3f}, "
      f"pop_frac = {cls.theta['pop_frac']:.5f}, "
      f"a_rain = {cls.theta['a_rain']:+.3f}")
print(f"  logL {cls_ll:,.1f}   {cls.n_forward_solves:,} forward solves   "
      f"{cls.seconds:.1f} s")

print("\n[PINN]")
pinn = InversePINN(synth, cfg, fixed, model="climate").train()
p = pinn.params()
pinn_mu = pinn.weekly_mu()
pinn_ll, pinn_aic, _ = score(synth, pinn_mu, 5)
print(f"  R0 = {basic_reproduction_number(p['beta_0'], fixed):.3f}, "
      f"pop_frac = {p['pop_frac']:.5f}, a_rain = {p['a_rain']:+.3f}")
print(f"  logL {pinn_ll:,.1f}   0 forward solves   {pinn.seconds:.1f} s")

for method, theta, ll, secs, solves in (
        ("classical", cls.theta, cls_ll, cls.seconds, cls.n_forward_solves),
        ("pinn", p, pinn_ll, pinn.seconds, 0)):
    rows.append(dict(
        stage="synthetic", window="national_2013_synthetic", method=method,
        R0=round(basic_reproduction_number(theta["beta_0"], fixed), 3),
        R0_truth=round(basic_reproduction_number(truth["beta_0"], fixed), 3),
        pop_frac=round(theta["pop_frac"], 6),
        pop_frac_truth=truth["pop_frac"],
        a_rain=round(theta["a_rain"], 3), a_rain_truth=truth["a_rain"],
        loglik=round(ll, 1), seconds=round(secs, 1), forward_solves=solves))

# ===========================================================================
# Stage 2 — the real windows
# ===========================================================================
print("\n" + "=" * 78)
print("STAGE 2 — real surveillance data")
print("=" * 78)

curves = {}
for name, w in cfg["windows"].items():
    df = pd.read_csv(processed / f"{name}.csv", parse_dates=["week_start"])
    data = Dataset.from_frame(df, label=w["label"])
    print(f"\n--- {w['label']} ---")

    cls = fit(data, cfg, fixed, model="climate", observation=OBS)
    cls_mu = predict(cls.theta, data, fixed, "climate", cfg)
    cls_ll, cls_aic, _ = score(data, cls_mu, len(cls.names))
    print(f"[classical] R0 = "
          f"{basic_reproduction_number(cls.theta['beta_0'], fixed):.3f}, "
          f"logL {cls_ll:,.1f}, {cls.n_forward_solves:,} solves, "
          f"{cls.seconds:.1f} s")

    pinn = InversePINN(data, cfg, fixed, model="climate").train(verbose_every=10000)
    p = pinn.params()
    pinn_mu = pinn.weekly_mu()
    pinn_ll, pinn_aic, _ = score(data, pinn_mu, 5)
    print(f"[PINN]      R0 = "
          f"{basic_reproduction_number(p['beta_0'], fixed):.3f}, "
          f"logL {pinn_ll:,.1f}, 0 solves, {pinn.seconds:.1f} s")

    curves[name] = (df, data, cls_mu, pinn_mu)
    for method, theta, ll, secs, solves in (
            ("classical", cls.theta, cls_ll, cls.seconds, cls.n_forward_solves),
            ("pinn", p, pinn_ll, pinn.seconds, 0)):
        rows.append(dict(
            stage="real", window=name, method=method,
            R0=round(basic_reproduction_number(theta["beta_0"], fixed), 3),
            pop_frac=round(theta["pop_frac"], 6),
            a_temp=round(theta.get("a_temp", np.nan), 4),
            a_rain=round(theta["a_rain"], 3),
            loglik=round(ll, 1), seconds=round(secs, 1), forward_solves=solves))

tab = pd.DataFrame(rows)
tab.to_csv(tables / "05_pinn_comparison.csv", index=False)

print("\n" + "=" * 78)
print(tab.to_string(index=False))

print("\nLikelihood gap on the real windows (positive means the classical fit is better):")
real = tab[tab["stage"] == "real"]
for name, grp in real.groupby("window"):
    g = grp.set_index("method")
    gap = g.loc["classical", "loglik"] - g.loc["pinn", "loglik"]
    speed = g.loc["pinn", "seconds"] / max(g.loc["classical", "seconds"], 1e-9)
    print(f"  {name:15s} Δ logL = {gap:+9.1f}   PINN took {speed:.1f}x longer, "
          f"performing 0 forward solves against "
          f"{int(g.loc['classical', 'forward_solves']):,}")

fig, axes = plt.subplots(len(curves), 1, figsize=(11, 3.6 * len(curves)))
for ax, (name, (df, data, cls_mu, pinn_mu)) in zip(np.atleast_1d(axes),
                                                   curves.items()):
    ax.bar(df["week_start"], data.cases, width=6, color="#c9ccd1",
           label="reported cases")
    ax.plot(df["week_start"], cls_mu, color="#8c1c13", lw=2, label="classical")
    ax.plot(df["week_start"], pinn_mu, color="#1f6f8b", lw=1.8, ls="--",
            label="PINN")
    ax.set_title(cfg["windows"][name]["label"])
    ax.set_ylabel("cases / week")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25, axis="y")
fig.tight_layout()
fig.savefig(figures / "05_pinn_comparison.png", dpi=150)
print(f"\nFigure: {figures / '05_pinn_comparison.png'}")
print(f"Table:  {tables / '05_pinn_comparison.csv'}")
