"""Pipeline step 33 — coverage when the data did not come from any fitted model.

Step 30 measured how often a reported interval contains the truth, using data
simulated from the same model family that is then fitted. A referee is entitled
to call that circular: real surveillance is not generated by a host--vector SEIR
with a Brière temperature response, so an interval that behaves well there may
behave badly in the only setting that matters.

This step generates from **outside** the family. The mis-specification chosen is
not arbitrary: the appendix of this paper demonstrates it in the data. Provincial
dengue epidemics are sums of district epidemics that peak at different times, and
a homogeneously mixing model reads the broader sum as slower transmission --- a
bias of $-29\\%$ in $R_0$ in one Pakistani province, where the aggregate estimate
falls below both districts it is composed of.

So the generator is **two patches**: two climate-forced epidemics sharing one
temperature series and one temperature exponent, seeded weeks apart, summed and
observed with negative-binomial noise. Every fitted model is single-patch. The
true temperature exponent is unambiguous --- both patches use the same one --- so
coverage remains well defined.

The question is not whether a single-patch fit is biased. It is, and the appendix
already shows so. The question is whether **the remedy this paper proposes still
works** when the model is wrong in a way real data is wrong. If the multiverse
interval covers here as well, the recommendation survives its hardest test. If it
does not, that is a limitation of the recommendation and belongs in the paper in
those words.
"""

from __future__ import annotations

import copy
import itertools
import multiprocessing as mp
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# `dengue_pk` must be imported before NumPy: see dengue_pk/_msvc_runtime.py.
from dengue_pk import load_config, resolve  # noqa: E402
from dengue_pk.climate import lagged_smoothed_rain, standardise  # noqa: E402
from dengue_pk.inference import (Dataset, fit, make_forcing,  # noqa: E402
                                 set_temperature_form)
from dengue_pk.locations import point_for  # noqa: E402
from dengue_pk.models import (FixedParams, IntegrationFailure,  # noqa: E402
                              initial_state, rk4_integrate, weekly_incidence)

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from scipy import stats  # noqa: E402

OBSERVATIONS = ("nb", "poisson")
RAIN_LAGS = (3, 5, 7)
TRAIN_FRACS = (1.0, 0.75)
STRUCTURES = ("hostvector", "seir", "hostvector_tempmort")
PARAM_SETS = ("central", "alt")

TRUE_A_TEMP = 1.00
TRUE_A_RAIN = 0.30
#: The second patch is seeded this many days after the first. Chosen from the
#: 46-day offset the two-patch model infers for Khyber Pakhtunkhwa in the
#: appendix, rather than picked to make the point.
PATCH_OFFSET_DAYS = 46.0
#: Relative size of the second patch.
PATCH_TWO_SHARE = 0.6

BASE = load_config()
raw = resolve(BASE, "raw")
tables = resolve(BASE, "tables")
clim_dir = raw / "climate_global"
OUT = tables / "34_out_of_family_coverage.csv"

FIXED = {"central": FixedParams.from_config(BASE, "fixed"),
         "alt": FixedParams.from_config(BASE, "fixed_alt")}


def cfg_for(observation, lag, structure):
    c = copy.deepcopy(BASE)
    c["model"]["temperature_form"] = "briere"
    c["model"]["structure"] = structure
    c["model"]["climate_forcing"]["rain_lag_weeks"] = lag
    c["inference"]["observation"] = observation
    c["inference"]["classical"]["n_restarts"] = 3
    return c


def two_patch_mean(theta: dict, data: Dataset, cfg: dict,
                   fixed: FixedParams) -> np.ndarray:
    """Expected weekly counts from two climate-forced patches, seeded apart.

    Both patches see the same climate and the same temperature exponent; they
    differ in size, seeding and start time. The sum is what a single-patch model
    will be asked to explain.
    """
    rho = cfg["model"]["fixed"]["rho_fixed"]
    total = np.zeros(len(data.days))
    for share, offset, i0 in ((1.0, 0.0, theta["i0_frac"]),
                              (PATCH_TWO_SHARE, PATCH_OFFSET_DAYS,
                               theta["i0_frac"] * 0.5)):
        local = data.days - offset
        t_end = float(max(local[-1] + 7.0, 7.0))
        forcing = make_forcing(theta, data, "climate", cfg)
        t, y = rk4_integrate(initial_state(i0), t_end, 1.0, forcing, fixed)
        pop = theta["pop_frac"] * data.population * share
        weekly = weekly_incidence(t, y, np.maximum(local, 0.0), pop)
        total += rho * np.where(local < 0.0, 0.0, weekly)
    return np.maximum(total, 1e-9)


def fit_window(package):
    meta, data_by_lag, seed = package
    label = f"{meta['country']}/{meta['unit']} {meta['window_start']}"
    if not data_by_lag:
        return label, [], "no usable lag"
    rng = np.random.default_rng(seed)
    ref = data_by_lag[min(data_by_lag)]

    set_temperature_form("briere")
    base_cfg = cfg_for("nb", min(data_by_lag), "hostvector")
    try:
        anchor = fit(ref, base_cfg, FIXED["central"], model="constant",
                     observation="nb")
    except Exception as exc:                        # noqa: BLE001
        return label, [], f"anchor failed: {exc}"
    k_hat = float(anchor.nb_k or 20.0)

    truth = dict(anchor.theta)
    truth.update(a_temp=TRUE_A_TEMP, a_rain=TRUE_A_RAIN)
    mult = make_forcing({**truth, "beta_0": 1.0}, ref, "climate",
                        base_cfg).on_grid(ref.days)
    truth["beta_0"] = float(anchor.theta["beta_0"]
                            / max(float(np.mean(mult)), 1e-12))
    try:
        mu_true = two_patch_mean(truth, ref, base_cfg, FIXED["central"])
    except IntegrationFailure:
        return label, [], "two-patch generation diverged"
    lam = rng.gamma(shape=k_hat, scale=np.maximum(mu_true, 1e-12) / k_hat)
    synth = rng.poisson(lam).astype(float)
    if synth.sum() < 100:
        return label, [], "simulated epidemic too small"

    rows = []
    for observation, lag, frac, structure, pset in itertools.product(
            OBSERVATIONS, RAIN_LAGS, TRAIN_FRACS, STRUCTURES, PARAM_SETS):
        if lag not in data_by_lag:
            continue
        d0 = data_by_lag[lag]
        full = Dataset(d0.days, synth, d0.temp_c, d0.z_rain, d0.population,
                       d0.label)
        train = full if frac >= 1.0 else full.head(
            int(round(len(full.days) * frac)))
        set_temperature_form("briere")
        cfg = cfg_for(observation, lag, structure)
        try:
            res = fit(train, cfg, FIXED[pset], model="climate",
                      observation=observation, start_from=truth,
                      n_starts_override=3,
                      fixed_nb_k=k_hat if observation == "nb" else None)
        except (RuntimeError, IntegrationFailure, ValueError):
            continue
        row = dict(country=meta["country"], unit=meta["unit"],
                   window_start=meta["window_start"], observation=observation,
                   rain_lag=lag, train_frac=frac, structure=structure,
                   params=pset, true_a_temp=TRUE_A_TEMP,
                   true_a_rain=TRUE_A_RAIN)
        for name in ("a_temp", "a_rain"):
            est = float(res.theta[name])
            se = float(res.stderr.get(name, np.nan))
            row[f"{name}_hat"] = round(est, 6)
            row[f"{name}_se"] = round(se, 6) if np.isfinite(se) else np.nan
        rows.append(row)
    return label, rows, None


def build_packages(n_windows: int):
    inv = pd.read_csv(tables / "12_global_windows.csv",
                      parse_dates=["start", "end"])
    inv = inv.iloc[:: max(len(inv) // n_windows, 1)].head(n_windows)
    print("Loading case data...", flush=True)
    cases = pd.read_csv(raw / BASE["data"]["opendengue"]["csv_name"],
                        usecols=["adm_0_name", "adm_1_name", "adm_2_name",
                                 "calendar_start_date", "calendar_end_date",
                                 "dengue_total"], low_memory=False)
    cases["start"] = pd.to_datetime(cases["calendar_start_date"], errors="coerce")
    cases["end"] = pd.to_datetime(cases["calendar_end_date"], errors="coerce")
    cases = cases[(cases["end"] - cases["start"]).dt.days + 1 == 7]
    cache: dict[str, pd.DataFrame | None] = {}

    def climate(slug):
        if slug not in cache:
            path = clim_dir / f"{slug}.csv"
            if not path.exists():
                cache[slug] = None
                return None
            with open(path, "r", encoding="utf-8") as fh:
                lines = fh.readlines()
            try:
                head = next(i for i, ln in enumerate(lines)
                            if ln.startswith("YEAR,"))
            except StopIteration:
                cache[slug] = None
                return None
            c = pd.read_csv(path, skiprows=head).replace(-999.0, np.nan)
            c["date"] = (pd.to_datetime(c["YEAR"].astype(str), format="%Y")
                         + pd.to_timedelta(c["DOY"] - 1, unit="D"))
            cache[slug] = c.set_index("date").sort_index()
        return cache[slug]

    smooth = BASE["model"]["climate_forcing"]["rain_smooth_weeks"]
    packages = []
    for idx, (_, w) in enumerate(inv.iterrows()):
        pt = point_for(w["country"], w["unit"], w["level"])
        if pt is None:
            continue
        name, lat, lon = pt
        slug = (f"{name.lower().replace(' ', '_').replace('/', '_')}"
                f"_{round(lat, 4)}_{round(lon, 4)}")
        clim = climate(slug)
        if clim is None:
            continue
        sub = cases[cases["adm_0_name"].astype(str).str.upper()
                    == str(w["country"]).upper()]
        if w["level"] == "national":
            sub = sub[sub["adm_1_name"].isna()]
        else:
            sub = sub[sub["adm_1_name"].astype(str).str.upper()
                      == str(w["unit"]).upper()]
            sub = sub[sub["adm_2_name"].isna()]
        sub = sub[(sub["start"] >= w["start"]) & (sub["start"] <= w["end"])]
        s = sub.groupby("start")["dengue_total"].sum().sort_index()
        if len(s) < 20:
            continue
        gaps = s.index.to_series().diff().dt.days.dropna()
        if not (gaps == 7).all():
            continue
        by_lag = {}
        for lag in RAIN_LAGS:
            c = clim.copy()
            c["rain_lagged"] = lagged_smoothed_rain(c["PRECTOTCORR"], lag, smooth)
            weekly = (c.resample("7D", origin=s.index.min())
                       .mean(numeric_only=True).reindex(s.index))
            if weekly[["T2M", "rain_lagged"]].isna().any().any():
                continue
            z_rain, *_ = standardise(weekly["rain_lagged"].to_numpy())
            days = (s.index - s.index.min()).days.to_numpy(float)
            by_lag[lag] = Dataset(days, s.to_numpy(float),
                                  weekly["T2M"].to_numpy(float), z_rain, 1e7,
                                  f"{w['country']}/{w['unit']}")
        if by_lag:
            packages.append(({"country": w["country"], "unit": w["unit"],
                              "window_start": str(w["start"].date())},
                             by_lag, BASE["seed"] + 104729 * idx))
    return packages


def rubin(est: np.ndarray, ses: np.ndarray, level: float = 0.95):
    ok = np.isfinite(est) & np.isfinite(ses)
    e, s = est[ok], ses[ok]
    m = len(e)
    if m == 0:
        return (np.nan,) * 3
    if m == 1:
        z = stats.norm.ppf(0.5 + level / 2)
        return e[0], e[0] - z * s[0], e[0] + z * s[0]
    q = float(np.mean(e))
    w = float(np.mean(s ** 2))
    b = float(np.var(e, ddof=1))
    t = w + (1.0 + 1.0 / m) * b
    if t <= 0 or not np.isfinite(t):
        return (np.nan,) * 3
    lam = (1.0 + 1.0 / m) * b / t
    df = (m - 1) / max(lam ** 2, 1e-12) if lam > 0 else np.inf
    crit = stats.t.ppf(0.5 + level / 2, max(df, 1.0)) if np.isfinite(df) \
        else stats.norm.ppf(0.5 + level / 2)
    half = crit * np.sqrt(t)
    return q, q - half, q + half


def report(d: pd.DataFrame) -> None:
    KEY = ["country", "unit", "window_start"]
    z = stats.norm.ppf(0.975)
    print("=" * 78)
    print("COVERAGE WHEN THE DATA CAME FROM TWO PATCHES AND THE MODEL HAS ONE")
    print("=" * 78)
    print(f"  {'parameter':>10}  {'conventional':>13}  {'multiverse':>11}")
    for name in ("a_temp", "a_rain"):
        est, se = d[f"{name}_hat"], d[f"{name}_se"]
        ok = np.isfinite(est) & np.isfinite(se) & (se > 0)
        t = d.loc[ok, f"true_{name}"]
        conv = ((est[ok] - z * se[ok] <= t) & (t <= est[ok] + z * se[ok])).mean()
        cov = []
        for _, g in d.groupby(KEY):
            q, lo, hi = rubin(g[f"{name}_hat"].to_numpy(),
                              g[f"{name}_se"].to_numpy())
            if np.isfinite(q):
                cov.append(lo <= float(g[f"true_{name}"].iloc[0]) <= hi)
        print(f"  {name:>10}  {conv * 100:12.1f}%  {np.mean(cov) * 100:10.1f}%"
              f"   ({ok.sum():,} fits, {len(cov)} outbreaks)")
    print()
    print("  Compare with step 30, where the data came from the fitted family:")
    print("    a_temp   conventional 82.9%   multiverse 100.0%")
    print("    a_rain   conventional 71.2%   multiverse  97.5%")
    print()
    print("  If the multiverse column holds up here it survives a structural")
    print("  error that real surveillance data demonstrably contains. If it")
    print("  does not, that is a limitation of the recommendation.")


def main():
    n_windows = int(sys.argv[1]) if len(sys.argv) > 1 else 40
    packages = build_packages(n_windows)
    n_workers = max(1, min(12, (mp.cpu_count() or 2) - 2))
    print(f"{len(packages)} windows prepared; {n_workers} workers\n", flush=True)
    rows, t0 = [], time.time()
    with mp.Pool(n_workers) as pool:
        for i, (label, got, why) in enumerate(
                pool.imap_unordered(fit_window, packages), 1):
            if why:
                print(f"[{i:3d}/{len(packages)}] {label:40s} SKIPPED: {why}",
                      flush=True)
                continue
            rows.extend(got)
            pd.DataFrame(rows).to_csv(OUT, index=False)
            rate = (time.time() - t0) / i
            print(f"[{i:3d}/{len(packages)}] {label:40s} {len(got):3d} fits  "
                  f"eta {rate * (len(packages) - i) / 60:5.1f} min", flush=True)
    d = pd.DataFrame(rows)
    d.to_csv(OUT, index=False)
    print(f"\n{len(d):,} fits in {(time.time() - t0) / 60:.1f} min\n")
    report(d)
    print(f"\nTable: {OUT}")


if __name__ == "__main__":
    main()
